### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by karlyn33** [karlyn33/hockeyLineup#7]
- [ ] I would like a new readme CONTRIBUTING.md
  - [ ] I want simple stuff with the good habit to participate at Hacktoberfest 2022
- [ ] with the link on the main README

**Comment by AnirbanBall** [comment]
Hey @karlyn33 I would like to work on this.

**Comment by karlyn33** [comment]
@AnirbanBall Yes go ahead. Don't hesitate if you have any questions.
Thank you

**Comment by karlyn33** [comment]
> Hey @karlyn33 I would like to work on this.

@AnirbanBall  With few days left before the end of Hacktoberfest 2022, I will take the first PR that is complete for the task.
